### ISSUE TITLE
TI-84 + does literally nothing but display nonsense

### ISSUE THREAD

**Issue by Grantrocks** [calc84maniac/tiboyse#3] opened 2024-02-05 23:55 UTC
Not to sure whats going on but trying to load the MarioLand.gb rom nothing happens and everything is frozen.
![20240205_185123](https://github.com/calc84maniac/tiboyse/assets/46384149/bd498887-d773-4f5b-b23b-cc8f79352c0a)

**Comment by Eeems** [comment] 2024-02-05 23:58
1. What OS version?
2. What version of TI-Boy?
3. What steps did you take?
4. What troubleshooting have you already done?

**Comment by calc84maniac** [comment] 2024-02-06 00:08
Duplicate of #2

**Closed as not planned by calc84maniac** 2024-02-06 00:08 UTC
